CREATE TYPE category AS ENUM ('open mic', 'audition', 'late show', 'showcase', 'host', 'feature', 'headliner');
CREATE TYPE gender AS ENUM ('male', 'female', 'other');
CREATE TYPE race AS ENUM ('white', 'black', 'asian', 'hispanic', 'native american', 'pacific islander');

CREATE TABLE comedian (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone CHAR(12),
    email VARCHAR,
    bio TEXT,
    notes TEXT,
    category CATEGORY,
    gender GENDER,
    age INTEGER,
    race RACE,
    passed TEXT,
    clean TEXT,
    ssn CHAR(11),
    street TEXT,
    city TEXT,
    st CHAR(2),
    zip VARCHAR(10),
    website TEXT,
    facebook TEXT,
    twitter TEXT,
    instagram TEXT
);