CREATE TABLE lineup (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    show_id INTEGER REFERENCES show(id),
    comedian_id INTEGER REFERENCES comedian(id),
    set_time INTEGER,
    order INTEGER
);